### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#652] opened 2023-05-22 11:54 UTC
The [Rust Book has been translated into Japanese](https://github.com/rust-lang-ja/book-ja). Let us see if we can reuse some of their terminology.

**Comment by mgeisler** [comment] 2023-05-25 12:21
Hey @momotaro1105, @keiichiw, @CoinEZ-JPN and other people interested in the Japanese translation.

Just a small note: I've created spreadsheets to help organize some of the other translations, see #684 for an example. That might be useful for you too.

**Comment by kantasv** [comment] 2023-05-28 05:05
Hi, I've read your misc-jp post and would love to contribute to this as a native Japanese speaker :) 
Do we already have the spreadsheet for the JA project? Or should I make one?
https://github.com/google/comprehensive-rust/issues/652#issuecomment-1562812496

**Comment by CoinEZ-JPN** [comment] 2023-05-30 01:57
hello, just checking - the next PR should come directly from my branch post fetch origin, correct?
and still to this #652?

**Comment by keiichiw** [comment] 2023-05-30 04:10
@CoinEZ-JPN If the branch on your forked repository is based on this repository's main branch and your commit message includes `#652`, that should be fine.

Note that it would be easier if one pull request translates only one chapter. That's said it'd be nice if you have branches such as `japanese-translate-ch-3` or `japanese-translate-ch-4` for each chapter.

**Comment by CoinEZ-JPN** [comment] 2023-05-30 09:10
@keiichiw hi thanks instructions
Is it alright if I commit the intro (ch.1 and 2) in a single PR?
The rest I will separate into its own branch.

@kantasv apol missed, not aware of what misc-jp is, but would be nice to work together - what do you need me to do?

**Comment by CoinEZ-JPN** [comment] 2023-05-30 11:32
@keiichiw pls ignore first comment, just created PR for just ch.0, the welcome page from `japanese-translation-ch-0`

**Comment by keiichiw** [comment] 2023-05-30 13:08
@mgeisler @CoinEZ-JPN @kantasv 
I just created [a spreadsheet](https://docs.google.com/spreadsheets/d/1qyu_59IlmxEHX4e5YnsxsjFWDY2o3YwIqE5PzMgKwnA/edit#gid=0) to gather the information on who is now working on which sections. Please take a look at it and put your name to the files you want to work on.

**Comment by keiichiw** [comment] 2023-05-30 13:09
@kantasv Thank you so much for offering to help! We've started translation. 
Please take a look at [po/ja.po](https://github.com/google/comprehensive-rust/blob/main/po/ja.po) and start translating whatever section you want!

Note that misc-jp is something Google internal. So, please avoid mentioning it in public places like here.

**Comment by CoinEZ-JPN** [comment] 2023-05-30 16:02
@kantasv - looking forward to working together 
FYI
- I'm simply working top to bottom atm
- done up to and incl. Ch.5 (PRs have NOT been created for all yet / spreadsheet is updated now)

**Comment by kantasv** [comment] 2023-05-30 23:05
Hi, @CoinEZ-JPN thanks for the headsup! Okay, then on my end I'll start from chapter corresponding to `src/async.md` with the top-to-bottom basis :)

**Comment by kantasv** [comment] 2023-08-05 07:03
Hi, seems like a lot of original English content have been updated so far, making ja.po file outdated. I try to figure out how to update translation according to `TRANSLATIONS.md`. Or if some of use are already familiar with updating po files, would be great if you do so :) 

Example of update in the original content
`po/ja.po`
https://github.com/google/comprehensive-rust/blob/c23da457ae62815477454290dde86d5b598c28df/po/ja.po#L13842
`src/concurrency/channels/bounded.md`
https://github.com/google/comprehensive-rust/blob/c23da457ae62815477454290dde86d5b598c28df/src/concurrency/channels/bounded.md?plain=1#L3

**Comment by mgeisler** [comment] 2023-08-07 07:50
Thanks @kantasv! As you can see in your #1054, every paragraph that has changes is now marked `fuzzy` in the translation. This is the signal to you and the fellow Japanese translators that the translation is out of date and it should be double-checked by a human:

- If the paragraph changed because of a typo fix, then it's easy: just remove the `fuzzy` marker from the translation.
- If the paragraph changed because of a rewrite, then the translation will need to be reworked before you remove the `fuzzy` marker.

**Comment by kantasv** [comment] 2023-08-07 12:25
Great. Thank you for pro tips. Okay, I'll resolve those fuzzy ones. Since we have many paragraph to translate, I've set up `cloud-translate` on my local computer, and seems it works to some extent. (Great workload reduction along with human correction!)

**Comment by HidenoriKobayashi** [comment] 2023-08-28 04:52
Hi! I'm interested in contributing to this! Please let me know if anyone comes up with a starting point that does not overlap ongoing work.

**Comment by kantasv** [comment] 2023-08-28 11:48
Hi @HidenoriKobayashi, glad to have you! Thanks to @keiichiw and @mgeisler , we have [this spreadsheet](https://docs.google.com/spreadsheets/d/1qyu_59IlmxEHX4e5YnsxsjFWDY2o3YwIqE5PzMgKwnA/edit#gid=0) that tracks who is working on which chapters.

**Comment by kantasv** [comment] 2023-08-28 12:34
This isn't itself a JA translation problem, but today when I try to hotreload for local environment, I had to use the following commands to display translations properly on mdbook locally: `rustup update` and `cargo install mdbook-i18n-helpers`.

Just leaving a tip for other translators who have been using old configurations!

**Comment by HidenoriKobayashi** [comment] 2023-08-29 01:25
Thanks @kantasv! I assume the workflow here is that you mark the "state" to "in-progress" when you start working. Let me know if otherwise.

**Comment by kantasv** [comment] 2023-09-03 01:31
Hi, @CoinEZ-JPN would you mind if I cover the "Basic Syntax" chapter? --- I saw your ticks in the [spreadsheet](https://docs.google.com/spreadsheets/d/1qyu_59IlmxEHX4e5YnsxsjFWDY2o3YwIqE5PzMgKwnA/edit#gid=1124000687). I might be able to offload your work :) But of course, this is a very interesting chapter, and if you're still working on it, please go for it!

**Comment by HidenoriKobayashi** [comment] 2023-09-11 06:42
How do folks deal with a case where some phrases in ja.po are not appropriately split. For example, src/bare-metal/microcontrollers/probe-rs.md:6 is split into two chunks, but I suppose it should really be one.

**Comment by henrif75** [comment] 2023-09-11 18:28
> How do folks deal with a case where some phrases in ja.po are not appropriately split. For example, src/bare-metal/microcontrollers/probe-rs.md:6 is split into two chunks, but I suppose it should really be one.

IIUC, it's being split because they're part of a bulleted list. With that said, I think you can consider both entry (probe-rs.md:6) as one, and enter the translation in either entry.

**Comment by HidenoriKobayashi** [comment] 2023-09-12 08:33
> IIUC, it's being split because they're part of a bulleted list. With that said, I think you can consider both entry (probe-rs.md:6) as one, and enter the translation in either entry.

Thank you for the suggestion! I think your advice perfectly solves my issue.

I wondered if that was due to the html tag (abbr) and that if there was any way to deal with it in ja.po (i.e. without affecting other language translations).

**Comment by kantasv** [comment] 2023-09-18 03:40
@CoinEZ-JPN Okay, I understand your situation. Since you already have some drafts, you can keep the chapter as yours for now :) I can work on other untranslated chapters!

**Comment by HidenoriKobayashi** [comment] 2023-10-10 01:05
I need to get the po file updated, but that might cause a conflict to somebody's working version. Please let me know if you want to get something done before that. I'm in no hurry. I plan to do the update this Friday (JST).

**Comment by mgeisler** [comment] 2023-10-10 07:40
> I need to get the po file updated, but that might cause a conflict to somebody's working version.

Just a small note: people will be able to merge in their work using [`msgmerge`](https://www.gnu.org/software/gettext/manual/html_node/msgmerge-Invocation.html) by hand:

```
msgmerge --update their-ja.po your-ja.po
```

That should use the messages found in `your-ja.po` as the source of truth, and it will clean up any unnecessary messages merged in from `their-ja.po`.

**Comment by kantasv** [comment] 2023-10-10 22:13
Hi @HidenoriKobayashi -san, I'm okay with refreshing the po file :) Thank you!

**Comment by ternbusty** [comment] 2023-11-04 05:40
Hello, as a native Japanese speaker, I'm eager to contribute to this project. I've already put my name on the spreadsheet. If it's alright, I would like to start with the translation in the src/control-flow/ directory.

**Comment by kantasv** [comment] 2023-11-04 06:25
Welcome, @ternbusty ! It's great to have you as another japanese translator!

**Comment by mgeisler** [comment] 2023-11-09 14:39
Hi all! I wanted to let you know about #1460. This is an update to mdbook-i18n-helpers which will remove ~6k lines from your PO file. It changes the way code blocks are processed: we now extract strings and comments directly.

You need to run `mdbook-i18n-normalize` on your PO file to preserve the translations found here: https://google.github.io/comprehensive-rust/ja/hello-world/small-example.html (and any other places where you have translated comments).

You can do this before/after refreshing the translation. See #1461 for an example PR which shows the state after normalization.

**Comment by kantasv** [comment] 2024-01-08 05:55
Hi, ja-translation folks, can someone refresh the `ja.po` file? (I'm also trying to refresh myself, but so far `POT-Creation` date is empty in `ja.po` in my environment.)

@HidenoriKobayashi -san, I'd like to seek your help if you don't mind refreshing the file.

**Comment by kantasv** [comment] 2024-01-08 06:00
Oh sorry, now I figured out and successfully generate ja.po with correct POT-creation date. I'll an MR for this, so no refresh actions required for ja folks. Cheers!

**Comment by henrif75** [comment] 2024-02-08 01:27
> To JA translators, FYI: @henrif75 is currently asking localization team to translate the remaining parts.
> 
> More context: [#1752 (comment)](https://github.com/google/comprehensive-rust/pull/1752#issuecomment-1909438780)
> 
> That being said, I'm not sure if this affects ongoing translation efforts being done here. Can we continue translation and fuzzy removal? @mgeisler @henrif75
> 
> I'm currently trying to removing fuzzy entries from day 1, but I'm afraid if this will be the duplicate effort.

I believe you can remove the fuzzy entries, because the file has been already refreshed with v2.

**Comment by mgeisler** [comment] 2024-02-20 11:14
> I believe you can remove the fuzzy entries, because the file has been already refreshed with v2.

Yeah, should be fine — `msgmerge` should handle this fine.

**Comment by HidenoriKobayashi** [comment] 2024-02-22 03:12
Hey folks, do you use poedit?
I finally had a bit of time to resume my translation work and then noticed that all the lines are marked with the warning sign (the yellow triangle with "!" in it).
If I remember correctly, poedit used to show the warning message for those lines if I select them. But now, I don't get anything.
Is it only me?

**Comment by kantasv** [comment] 2024-03-02 09:21
Hi, @HidenoriKobayashi -san. The Poedit behaviors you mentioned weren't reproducible in my environment:

- My Poedit version: 3.51, Mac OS: Sonoma 14.2.1
- Triangle explamation icons on top of the text lists are visible: 
  - Source texts do not always have explamation icons — only some but not all
  - Clicking a line with the icon shows me concrete feedback, such as `翻訳は"."で終える必要があります。`

Do you still have the same issue?

**Comment by kantasv** [comment] 2024-03-05 23:49
I haven't been able to work on the translation but I'm refreshing translation from the beginning to sections before Day1 AM. I'll open an MR soon :)

**Comment by henrif75** [comment] 2024-03-06 17:35
> I haven't been able to work on the translation but I'm refreshing translation from the beginning to sections before Day1 AM. I'll open an MR soon :)

Hi @kantasv ,
Can you hold doing this? I'm going to send the professional translation PRs soon, and you might have to change your PR.
Thanks.

**Comment by kantasv** [comment] 2024-03-08 08:35
@henrif75 Sure, thanks for the heads up :)

**Comment by HidenoriKobayashi** [comment] 2024-03-15 02:24
> Hi, @HidenoriKobayashi -san. The Poedit behaviors you mentioned weren't reproducible in my environment:
> 
> * My Poedit version: 3.51, Mac OS: Sonoma 14.2.1
> * Triangle explamation icons on top of the text lists are visible:
>   
>   * Source texts do not always have explamation icons — only some but not all
>   * Clicking a line with the icon shows me concrete feedback, such as `翻訳は"."で終える必要があります。`
> 
> Do you still have the same issue?

Thanks @kantasv for the message! It somehow works as intended now.

**Comment by henrif75** [comment] 2024-03-15 03:07
> By the way, when the professional translations are merged, what else is left for this issue?

There will be several translations that will need to be reviewed because they're marked as "fuzzy". Besides that, the original course is constantly updated and improved, and eventually translations need to catch up.

**Comment by HidenoriKobayashi** [comment] 2024-04-18 04:16
@henrif75 Regarding the profession translation PRs, are the comments handled by yourself or they go back to the translation team?

I had naively regarded that they will be read by someone who can read Japanese. If that is not the case, maybe I should try to convert all my comments to suggestions that you can apply. Well, that obviously takes some time, but it's doable.

**Comment by mgeisler** [comment] 2024-04-18 10:57
> > By the way, when the professional translations are merged, what else is left for this issue?
> 
> There will be several translations that will need to be reviewed because they're marked as "fuzzy". Besides that, the original course is constantly updated and improved, and eventually translations need to catch up.

I agree. I also wonder if we should mark the per-language issues as closed after we publish the first version? I think it could make sense to mark that milestone.

**Comment by kantasv** [comment] 2024-04-21 02:21
Hi @mgeisler , could we add @HidenoriKobayashi -san to the repo? We already added Hidenori-san to CODEOWNERS, but now I remember a comment from you:

> You need write permission on the repository to review things (we enabled this after we got a few spam reviews).

(https://github.com/google/comprehensive-rust/pull/1472#issuecomment-1807890068)

**Comment by mgeisler** [comment] 2024-04-22 07:13
Yes, certainly! Welcome @HidenoriKobayashi!

**Comment by HidenoriKobayashi** [comment] 2024-07-08 04:10
Now that the professional translation PRs went in (thanks @henrif75!), I think we can close this issue to mark that milestone. Although I see many parts that are behind the English main version, I think those should be easier managed if we handle them separately from this one.

What I'd like to do after this is that we create an issue to catch-up with the English main version every quarter or so. Plus, if there's something wrong, we create a specific issue and correct that.

Does anyone have an objection? (If so, please re-open this issue)

**Closed by HidenoriKobayashi** 2024-07-08 04:10 UTC
Labels: translation

**Comment by mgeisler** [comment] 2024-07-09 17:10
> What I'd like to do after this is that we create an issue to catch-up with the English main version every quarter or so. Plus, if there's something wrong, we create a specific issue and correct that.

That sounds like a great idea, thanks @HidenoriKobayashi!
