### ISSUE TITLE
Korean and Brazilian portuguese languages are not accessible

### ISSUE THREAD

**Issue by Mahmod** [google/comprehensive-rust#435] opened 2023-02-17 21:47 UTC
I checked out the latest code and I ran the code locally using "mdbook test" command.

I got these warnings

```
2023-02-17 21:34:58 [WARN] (mdbook::book): preprocessor.links.after contains "gettext", which was not found
2023-02-17 21:34:58 [WARN] (mdbook::book): preprocessor.svgbob.before contains "gettext", which was not found

```

The access for http://localhost:3000/ was fine and the navigation for different pages was Ok.

when I clicked the globe icon to change language to either Brazilian , I got redirection to 
http://localhost:3000/pt-BR/index.html. and error message
```
Document not found (404)
This URL is invalid, sorry. Please use the navigation bar or search to continue.
```

Same issue happens for Korean language but the I got redirected to
http://localhost:3000/ko/404.html

**Comment by mgeisler** [comment] 2023-02-18 09:31
Hey @Mahmod,

At the moment, you need more than just a `mdbook serve` command to generate the translations. You need to replicate the steps in [`publish.yml`](https://github.com/google/comprehensive-rust/blob/main/.github/workflows/publish.yml). It basically runs `mdbook build` once per language and makes sure to output the result into the correct subfolders.

I want to simplify this, see #423 for that. Perhaps you can help here?

**Comment by mgeisler** [comment] 2023-02-19 08:34
I'll close this for now since things are working as intended (or at least working as per the instructions in [TRANSLATIONS.md](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md) :smile:

**Closed by mgeisler** 2023-02-19 08:34 UTC

**Comment by Mahmod** [comment] 2023-02-21 01:46
Thank you for the quick feedback, I'll follow the instructions for my work on arabic language support .

**Comment by mgeisler** [comment] 2023-02-21 06:50
That will be great! I'm curious to see if we need to change anything to get a right-to-left language working.
